# -*- coding: utf-8 -*-
"""Alignment & Gaps rows, and the Pre-Day 1 document map."""

# Ref, Area, Screen(s), What the mockup does today, Source of truth,
# What the source says, Verdict, Action needed, Owner, Priority
ALIGNMENT = [
("G-01","Compliance pack — volume","NH P-05",
 "Shows six global-core documents for a US hire, each acknowledged separately on one page.",
 "CR PC Onboarding Workflow Documents (current-state Workday BP)",
 "The live business process serves 416 document instances across 357 unique titles. A US hire receives ~36 instances, including a 28-document bundle: the US handbook, 25 state handbook addenda, the benefits booklet and GovDocs. Poland receives ~57, Brazil ~28, Japan ~19.",
 "GAP OPEN",
 "The mockup shows the intended future core, not what is served today. Decide explicitly what stays pre-Day 1, what moves to Day 1+, and what is retired. Until that is decided the mockup understates the task by an order of magnitude.",
 "Legal / PEX / HR Ops","1 — Blocks build"),

("G-02","Compliance pack — language","NH P-01c, NH P-05",
 "Preferred language is a user-selected field on Tab 3 which drives the language of policy documents.",
 "PRD v1.4 (Data Protection Policy section) + Global DPN pack (20 translations)",
 "The DPN 'must be auto displayed in the employee's local language for countries where a translated version is required'; English for all other countries. Language is derived from country, not chosen by the employee. Approved translations and the country list are supplied.",
 "CONFLICT",
 "Change the mechanism: derive document language from country of hire, and demote the preference field to a comms/UI preference (or drop it). Revise assumption A-03 — it currently describes the wrong model.",
 "Privacy / DIO","1 — Blocks build"),

("G-03","Reading material — factsheet and handbook","NH P-05",
 "Company factsheet and the country employee handbook are grouped separately as reading material with no acknowledgement.",
 "Commonality Design Logic Tracker rows 3 and 8",
 "Factsheet: Pre-Day 1, no acknowledgement, single global object with localised versions. Handbook: Pre-Day 1 through Day 30, no acknowledgement, country-conditional reference, key policies acknowledged separately as universal tasks.",
 "ALIGNED",
 "None. Note the workbook's own question of whether the factsheet is essential pre-boarding at all or better placed on Day 1.",
 "PEX","4 — Monitor"),

("G-04","Compliance pack — where content lives","NH P-05",
 "Code of Business Conduct is treated as an external site: opens in a new tab, needs Equinix sign-in, returns to a page that remembers position and unlocks the acknowledgement.",
 "PRD v1.4 architectural question",
 "Explicitly unresolved: 'can we point to our global/universal compliance policies page via MyHR (where all versions/translations live) and still get a check-the-box acknowledgement, or do we need to copy the artifacts directly into ServiceNow (or Workday)?'",
 "GAP OPEN",
 "Settle the architecture. The mockup has picked link-out-and-return for one document and inline for five; that split should be a decision, not an accident of which source described which.",
 "DIO / Legal","1 — Blocks build"),

("G-05","Benefits — dependency","NH P-00 Coming up",
 "Benefits enrolment shows as a Coming up card that opens 30 days before the start date.",
 "PRD v1.4 UC-S2-06",
 "Card enabled 30 days before start. Dependency: a Workday pre-hire employee ID is required before the task can appear, because Darwin and Benefax use employee number as the unique identifier. No ServiceNow integration is needed — a link suffices. Both platforms remain until at least 2028.",
 "GAP CLOSED",
 "Add the employee-ID dependency to the card's explanation, so the disabled state says what it is actually waiting for rather than only naming a date.",
 "Benefits COE / DIO","3 — Content"),

("G-06","Corporate card","HM subtraction review",
 "Listed as Undecided and deliberately not built, on the grounds that the source row was truncated.",
 "PRD v1.4 (Citi Corporate Card section)",
 "Now fully specified. A pre-start manager task: 'New hire will travel on behalf of Equinix and be provided a corporate card' — yes/no. If yes, conditional logic creates a task for the new hire on Day 2 (post start date): PDF review plus e-signature. A weekly extract of completed agreements goes to Accounts Payable, who submit to Citi; Citi then sends an individualised application link. Extract fields: first name, last name, email, cost centre, country, EQXID, employee number, shipping address. Contingent workers out of scope. Citi cannot host the agreement, so it lives in Workday and/or ServiceNow.",
 "SUPERSEDED",
 "Build it. Manager side: a yes/no framed around travel, not a generic entitlement. New hire side: a Day 2 boundary card, since it is explicitly post-start. Retire assumption M-12. Open sub-question the PRD itself asks: what is the task called in the portal?",
 "Finance / PEX / DIO","2 — Build now"),

("G-07","Personal details — ownership and field list","NH P-01, banking boundary",
 "Renders the full personal-details wizard with banking as a locked boundary card, flagged as a proposal pending an ownership ruling.",
 "PRD v1.4 (Payroll / ADP mandatory fields)",
 "New requirement: the Workday scrum team is building mandatory fields required for the ADP payroll integration, to be surfaced through 'a new, globally universal form in the preboarding SNOW portal experience'. An 80/20 split — core universal fields for 80% of hires, conditional logic for local compliance fields for the remaining 20%. Expected Q3 and explicitly in scope for this PRD.",
 "NEW REQUIREMENT",
 "This is the same form the mockup already draws, arriving from the payroll side with a defined field list. Reconcile the wizard against the mandatory-field list when it lands. It also largely answers the ownership question that assumption A-10 is parked on.",
 "HR Ops / Payroll / DIO","1 — Blocks build"),

("G-08","Identity document capture","NH P-01a",
 "Identity and right-to-work documents are captured on Tab 1, alongside country of hire, with a visible callout that this overlaps a separate task and is a proposal.",
 "Future State workflow Seq 11; NH spec A-29 / A-30",
 "Country-specific employment checks remain their own conditional task ('Complete I-9 Section 1 for U.S., right-to-work or medical checks where required'), routed in the portal or deep-linked. Nothing endorses capturing the document twice.",
 "GAP OPEN",
 "Decide whether capture-once is worth the overlap. The PEX document-sequencing work reportedly already specifies which documents come early and which come late — get that before building either version.",
 "PEX / Legal","2 — Build now"),

("G-09","Inside Equinix","NH P-00 rail",
 "Parked in the right-hand rail as reference reading, expanding to name the six chapters, with the carousel recorded only as future intent.",
 "PRD v1.4 UI request",
 "Now specified: 'Have a carousel at the top of the onboarding portal UI that rotates through the Inside Equinix sections (chapters 01-06)... in addition to the carousel, we will link to this in the right hand bar for Additional Reading content. No tasks but turn on access and the carousel as pre-hire content.' The same content also appears in New Hire Orientation and in the manager's weekly task list.",
 "GAP CLOSED",
 "Build the carousel above the progress tracker and keep the rail link. Assumption A-35's three-way question is answered — it is both, and it is not a task. This is the substance of the Consideration tab.",
 "PEX / Employee Comms","2 — Build now"),

("G-10","Compliance pack — structure","NH P-05",
 "One page presenting several documents, each acknowledged separately, with a single submit at the end.",
 "PRD v1.4 (Global, Universal Compliance Policies)",
 "'Ideally this policy will wrap under all other global compliance policies into one umbrella task, Global Compliance Policies, with subtasks — e.g., Data Protection Policy.' The umbrella task and its subtask both remain outstanding until acknowledgement is complete.",
 "ALIGNED",
 "None — the mockup already implements umbrella-plus-subtasks. Worth naming the page 'Global Compliance Policies' to match the language the build will use.",
 "DIO","4 — Monitor"),

("G-11","Buddy visibility","HM H-07 → NH P-00 rail",
 "Implements both rules with a switch: the new hire sees the buddy from assignment, or 72 hours before start. Flagged as a conflict on the handoff map and on the buddy screen.",
 "HM spec OI-22 (raised against this prototype) + PRD S2-US18 AC2",
 "The specification says the buddy contact card is visible to the new hire from 72 hours before the start date. The new hire prototype shows the buddy from the moment of assignment. Neither source says whether the buddy has accepted before their name is shown — which matters, because the manager can reassign up to Day −3.",
 "CONFLICT",
 "Pick a rule. Two sub-questions to settle with it: does the buddy accept before the new hire sees the name, and what happens on the screen if the manager reassigns after the new hire has already seen it?",
 "PEX / buddy programme","1 — Blocks build"),

("G-12","Suggested team network — platform","HM H-11 → NH network",
 "Built as a net-new manager task: pick at least five people, write a reason for each, each is notified, the list and reasons reach the new hire with bookable 1:1 slots. Flagged as the only item that adds manager work.",
 "Onboarding Workday deck (native platform capability)",
 "Workday Onboarding already ships 'Select People to Meet for New Hire' and 'Select Helpful Contacts for New Hire' as administrator/manager setup, surfaced on the new hire's onboarding dashboard as 'People to Meet' and 'Helpful Contacts'.",
 "GAP OPEN",
 "This changes the argument materially. The question is no longer 'should we build a new task' but 'do we use the capability that already exists, and in which platform'. Re-cost M-10 before deciding whether it adds work at all.",
 "DIO / PEX","2 — Build now"),

("G-13","Welcome note — platform","HM H-10 → NH P-00",
 "Built as a superset manager screen: pre-filled boilerplate, an editable personal line, and a read-only generated first-week block.",
 "Onboarding Workday deck (native platform capability)",
 "Workday Onboarding already ships 'Customize a Welcome Memo' for administrators and a 'From My Manager — Personalized Message' block on the new hire's dashboard.",
 "GAP OPEN",
 "Same question as G-12: use the native capability or build it. The generated first-week block is the part that is genuinely additive, because it is drawn from the new hire's real task list.",
 "DIO / PEX","3 — Content"),

("G-14","Proxy and delegation","HM H-03",
 "A Day 1 proxy is captured with the other logistics, applies to this hire only, and is marked as having undefined permissions.",
 "PRD v1.4 (Proxies) + HM spec OI-12",
 "Broader than the mockup: 'People Experience and Hiring Managers will need the ability to add a proxy to (1) take action on their behalf in the system and/or (2) enable visibility to new hire's status.' So proxy is a standing capability for two personas, not a Day 1 field for one.",
 "GAP OPEN",
 "Separate the two: a standing delegation capability for PEX and managers, and the narrower question of who meets the new hire on Day 1. The mockup currently conflates them.",
 "DIO","2 — Build now"),

("G-15","Buddy — definition and duration","HM H-07, NH rail",
 "Describes the buddy as one person for culture and logistics, distinct from the network and the reporting line.",
 "Buddy Program deck",
 "'An onboarding buddy is an employee who partners with a new or transferring employee during their first 3+ months on the job. The buddy offers advice, resources, and guidance regarding the day-to-day aspects of working in their role... They may also offer encouragement and suggestions as they introduce the new employee to the culture.'",
 "ALIGNED",
 "Definition now sourced rather than assumed. One adjustment: the relationship runs 3+ months, so the portal should not frame the buddy as a Day 1 fixture. Also covers transferring employees, not only new hires.",
 "PEX","3 — Content"),

("G-16","Equinix credentials","NH P-00 Coming up; HM subtraction review",
 "Shows 'Collect your Equinix credentials' as a Day −1 Coming up card with its contents flagged as undocumented. The subtraction review claims the manager no longer hands over usernames and passwords.",
 "Future State Seq 1 + live UAT portal + Hiring Manager Checklist (2019)",
 "Three sources disagree. The future-state welcome email includes 'username, initial password/reset instructions'. The live portal has a separate new-hire task of the same name due one day before start. The current manager checklist still instructs managers to provide the username and the password.",
 "CONFLICT",
 "Establish what the credentials task actually contains before the 'two manager tasks eliminated' claim is used outside this workstream. It is the strongest subtraction claim on the manager side and it currently rests on three sources that do not agree.",
 "DIO / PEX","2 — Build now"),

("G-17","Equipment — problem statement","NH equipment, HM H-04",
 "Equipment is first in the list with the earliest due date, and both sides read one status table naming who each item waits on.",
 "Equipment provisioning deck (Fault line #4)",
 "'Day One Readiness: Inconsistent human connection experiences on Day 1, late or missing laptops, unconfigured devices, missing badges, limited live IT support and no swag — prevents new hires from being productive, creating a negative first impression.'",
 "ALIGNED",
 "None. The named fault line is direct support for equipment-first (A-33) and for the status table being more valuable than the picker.",
 "EUT","4 — Monitor"),

("G-18","Source integrity — sequence numbers","All",
 "Cites task sequence numbers from the future-state workbook throughout the register.",
 "Future State workflow file; HM spec OI-14",
 "The master inventory holds 67 task rows while the three phase tabs hold 68 between them. The missing row is a manager task. Every sequence number from 34 onward therefore refers to a different task depending on which tab is read.",
 "GAP OPEN",
 "Correct the workbook before any sequence number is used as a build key. Until then, cross-references in this planner and in both UI specs are ambiguous above 34.",
 "Onboarding PM","2 — Build now"),

("G-19","Third persona — People Experience","Not built",
 "Only two portals exist in the mockup. PEX appears throughout as an audience — dashboards, escalation target, contact card — but has no screens.",
 "Both UI specs (PEX named as audience); no PEX UI spec available in this session",
 "The new hire spec and manager spec both give PEX a dashboard view across all their new hires, an escalation destination, and proxy rights. No specification for those screens was available here.",
 "GAP OPEN",
 "Get the PEX UI spec, or confirm it does not exist yet. The manager's readiness view is close to what a PEX view needs, scoped across many hires instead of one — worth checking before it is designed twice.",
 "PEX","2 — Build now"),

("G-20","Swag and uniform","Not built",
 "Named as a deliberate exclusion on the new hire side.",
 "Future State Seq 14 vs both UI specs",
 "The future-state workflow carries 'Submit uniform / swag preferences' as a conditional pre-Day 1 task for IBX and location-based roles. Both UI specs record swag as out of scope, and the new hire spec records it as out of scope even for Q4. The equipment deck names 'no swag' as part of the Day One Readiness fault line.",
 "CONFLICT",
 "Minor but real: one source has it as a pre-Day 1 task, two have it out of scope, and a fourth names its absence as a problem. Settle whether it is in the portal at all.",
 "CRE / IBX / PEX","3 — Content"),

("G-21","Confirm start date","Not built",
 "The start date is displayed in the header and on the job description, but there is no task to confirm it or request a change.",
 "Future State Seq 4",
 "'Confirm start date' is a separate required pre-Day 1 new hire task: 'Confirm start date or submit change; portal updates dependent due dates and tasks.'",
 "GAP OPEN",
 "A required task is missing from the mockup. It also matters structurally, because every due date in the portal is an offset from the start date — a change has to cascade.",
 "PEX / HR Ops","2 — Build now"),

("G-22","Background check","NH P-00 other teams",
 "Shown as a status-only card under 'Handled by other teams' with no action.",
 "Future State Seq 3",
 "'Launch First Advantage / background check from portal; show status and clear notification when available.' It is a required new hire task with an action, not only a status.",
 "GAP OPEN",
 "The mockup understates this. Either the new hire launches it from the portal, in which case it belongs in Do these now, or it is genuinely passive — the source says the former.",
 "Background check / PEX","2 — Build now"),

("G-23","Day 1 information","NH P-00 Coming up; HM H-03",
 "First-day details open three days before the start date and carry what the manager confirmed.",
 "Future State Seq 16 + PRD S3-US07",
 "Day 1 information is sent three business days before the start date, auto-pulling office, parking, map, who to ask for, what to expect and dress code from the assigned blueprint.",
 "ALIGNED",
 "None. The one open piece is whether a manager can override blueprint values — see the Portal Map note on H-03.",
 "PEX / CRE","4 — Monitor"),

("G-24","US state handbook addenda","NH P-05",
 "Not represented — the mockup shows one country handbook as reference material.",
 "CR PC Onboarding Workflow Documents",
 "Every US hire receives all 25 state handbook addenda in one bundle, regardless of which state they work in. Separate state-conditional rows exist for California, New Jersey, Texas, Massachusetts and New York, so conditionality is possible in the same process.",
 "GAP OPEN",
 "A Colorado hire currently receives 24 addenda that do not apply to them. This is the clearest single example of the commonality workbook's case, and the cheapest visible win in the pack.",
 "Legal / HR Ops","2 — Build now"),

("G-25","Country volume outlier","NH P-05",
 "Uses the United States as the worked example and Japan as the country variant.",
 "CR PC Onboarding Workflow Documents",
 "Poland receives the largest document set at ~57 instances, ahead of the United States (~36), Brazil (~28) and Japan (~19). Poland also carries occupational-risk conditionals by job profile and separate work-from-home appendices.",
 "GAP OPEN",
 "If the portal renders a per-country list, Poland is the stress test, not the United States. Worth drawing before build, because a 57-item list is a different screen from a 6-item one.",
 "Legal / PEX","3 — Content"),
]

# ---- Pre-Day 1 document map ----
# Family, Document(s) today, Who receives it, Instances, Ack today, Future treatment, In mockup, Gap / action
DOCUMENTS = [
("1.1 Code of Business Conduct","Code of Business Conduct (Dec 2024) + translations",
 "Global core — all countries except BR, CA, DE, CL, PR, JP","2 (global rows)","Yes",
 "Global source with translations only. Avoid country copies unless Legal directs.",
 "Yes — external-site treatment with return path",
 "Settle whether it is linked from MyHR or copied into the portal (see G-04)."),
("1.2 Acceptable Use Policy","Global Acceptance Use Policy",
 "Global core, all countries","2 (global rows)","Yes",
 "One global acknowledgement plus a country addendum when the rule triggers. Japan, Korea and France are addendum candidates.",
 "Yes — with the Japan addendum nested inside the policy",
 "Addendum trigger table still pending legal review, so the content is illustrative."),
("1.2 › Information Governance","Information Governance Approach",
 "Global core, all countries","2 (global rows)","Yes — but at Week 1",
 "Single universal task plus translated content. No country logic. Placed at Week 1.",
 "Shown under Coming up as a first-week item",
 "The only compliance artifact placed at Week 1 with no rationale recorded. Confirm or move."),
("1.3 Whistleblower Protection","Whistleblower Protection Policy (2019 global)",
 "Global core, all countries","2 (global rows)","Yes",
 "Universal task plus translations. Retire older documents.",
 "Yes — inline with scroll gate","None."),
("1.4 Securities Trading Policy","Securities Trading Policy — Insider Trading Policy (Global 2019)",
 "Global core, all countries","2 (global rows)","Blank in the source",
 "Universal task plus translations.",
 "Yes — assumed to require acknowledgement (A-19)",
 "Acknowledgement requirement is blank in the commonality workbook. Legal to confirm."),
("2.1 Employee Data Privacy Notice","Equinix Global Employee Data Privacy Notice (FINAL July 2026) — 20 language PDFs supplied",
 "All new hires; country addendum where required","Supplied as a separate pack","Yes",
 "One global notice, auto-displayed in the local language where a translation is required, English otherwise, plus a country addendum library.",
 "Yes — but language is driven by a user preference, not by country",
 "CONFLICT — see G-02. Change the language mechanism to country-derived."),
("2.2 Self-Identification Privacy Notice","Self-ID DPN Addendum",
 "All new hires","—","Yes",
 "One artifact with translated content only.",
 "Yes — paired with the self-ID block on Tab 3",
 "Categories in the self-ID block remain country-specific and undefined (A-07)."),
("8.1 Company Factsheet","Equinix Company Factsheet 2026",
 "Global core, all countries","2 (global rows)","No",
 "Single global content object, no translation — it is not a compliance document.",
 "Yes — grouped as reading material, no acknowledgement",
 "Open question in the workbook itself: is it needed pre-boarding or better on Day 1?"),
("4.1 Country Employee Handbook","US Employee Handbook (Nov 2024) + 25 state addenda; APAC 2022 template; EMEA 2018 base + country supplements",
 "Country-conditional; the US bundle goes to every US hire","28 in the US bundle alone","No — reference",
 "Country-appropriate handbook as reference. Key policies acknowledged separately as universal tasks.",
 "Partly — one country handbook shown as reference material",
 "GAP — see G-24. Every US hire receives all 25 state addenda regardless of work state."),
("4.2 Employment Rules (Japan)","就業規則 (Japanese employment regulations), 2025-04-01",
 "Japan","19 across three Japan rows","Yes",
 "Country-specific legal format — a genuine outlier from the handbook model.",
 "Not represented; Japan appears only as an AUP addendum",
 "Japan needs its own treatment, not an addendum. Flagged as a format outlier in the workbook."),
("5.1 Benefits Enrollment","2026 Equinix U.S. Benefits Booklet; country plan documents",
 "Country and platform conditional","Bundled into country packs","Varies",
 "Conditional routing until a global benefits platform exists. Darwin and Benefax both remain until at least 2028.",
 "Shown under Coming up, opens 30 days before start",
 "Add the Workday employee-ID dependency to the disabled state (G-05)."),
("6.1 Tax Withholding","W-4 (US), TD1 (CA), local declarations",
 "Country-specific regulatory","Within country packs","Yes where required",
 "Country-specific; no global core component to merge into.",
 "No — named as a deliberate exclusion",
 "Confirmed out of scope. Payroll owns it."),
("3.3 Bank / Payment Details","Direct deposit / payment authorisation",
 "Country-specific banking","Within country packs","Yes",
 "Country-specific class of its own; owned by Payroll.",
 "No — shown as a locked boundary card on Tab 3 and the task list",
 "Confirmed deliberate exclusion. Timing still disputed across three sources (A-11)."),
("7.1 Right to Work","I-9 (US), country right-to-work checks, medical checks where required",
 "Country-specific regulatory","Within country packs","Yes where required",
 "Do not globalise content; globalise framework and timing only.",
 "Shown as available now, completed in its own system; medical check for Japan",
 "Identity capture on Tab 1 overlaps this — decide capture-once or not (G-08)."),
("7.2 Employment Agreement","Offer letter / employment contract; country contracts",
 "Country-specific legal","Within country packs","Yes",
 "Signed in Stage 1 before this portal exists for the new hire.",
 "Referenced read-only on the job description page; never re-signed",
 "Correct — re-signing would be a duplicate legal act."),
("Local — Brazil","Código de Conduta, Política Negociação de Títulos, Vale Transporte, Contribuição Sindical, dental and pharmacy forms and others",
 "Brazil","~28","Mixed",
 "Not yet analysed in the commonality workbook beyond the handbook row.",
 "No","Second largest country pack. Needs its own analysis pass."),
("Local — Poland","Occupational-risk documents by job profile, WFH appendices 1 and 4, and a 20-document and 21-document bundle",
 "Poland, with job-profile and work-arrangement conditionals","~57","Mixed",
 "Not yet analysed.",
 "No","LARGEST pack. If the portal renders per-country lists, Poland is the stress test (G-25)."),
("Local — Corporate card","Credit Card Employee User Agreement for Company Pay",
 "Employees who will travel on behalf of Equinix; contingent workers out of scope","New in PRD v1.4","Yes — e-signature",
 "Manager yes/no pre-start; new hire PDF review plus e-signature on Day 2; weekly extract to Accounts Payable, then Citi issues the application link.",
 "No — currently listed as Undecided and not built",
 "SUPERSEDED — build it (G-06). Note it is Day 2, not pre-Day 1."),
]
