"""Build exec-view/geo.js from Natural Earth 110m (world-atlas@2.0.2 countries-110m.json).

Usage: python3 build_geo.py <countries-110m.json> <out geo.js>
Source: https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json
Projection: Web Mercator (what Tableau's background maps use), Antarctica dropped,
clipped to 58S-78N, fitted to a 1000-unit-wide viewBox.
"""
import json, math, sys

src, out = sys.argv[1], sys.argv[2]
topo = json.load(open(src))
sx, sy = topo["transform"]["scale"]
tx, ty = topo["transform"]["translate"]

arcs = []
for arc in topo["arcs"]:
    x = y = 0
    pts = []
    for dx, dy in arc:
        x += dx; y += dy
        pts.append((x * sx + tx, y * sy + ty))
    arcs.append(pts)

def arc_pts(i):
    return arcs[i] if i >= 0 else arcs[~i][::-1]

LAT_MAX, LAT_MIN = 78.0, -58.0
def merc(lat):
    lat = max(LAT_MIN, min(LAT_MAX, lat))
    return math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
W = 1000.0
Y0, Y1 = merc(LAT_MAX), merc(LAT_MIN)
H = W * (Y0 - Y1) / (2 * math.pi)
def proj(lon, lat):
    return ((lon + 180) / 360 * W, (Y0 - merc(lat)) / (Y0 - Y1) * H)

def ring_d(ring):
    pts = []
    for i in ring:
        p = arc_pts(i)
        pts.extend(p if not pts else p[1:])
    # unwrap longitudes so rings crossing the antimeridian (Russia, Fiji) stay continuous;
    # the overhang is clipped by the viewBox instead of smearing a band across the map
    un = [pts[0]]
    for lon, lat in pts[1:]:
        prev = un[-1][0]
        while lon - prev > 180: lon -= 360
        while lon - prev < -180: lon += 360
        un.append((lon, lat))
    xy = [proj(*p) for p in un]
    # drop rings that wrap the antimeridian badly (tiny artefacts)
    s = "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in xy) + "Z"
    return s

countries = []
for g in topo["objects"]["countries"]["geometries"]:
    name = g.get("properties", {}).get("name", "")
    if name == "Antarctica" or "arcs" not in g:
        continue
    polys = g["arcs"] if g["type"] == "MultiPolygon" else [g["arcs"]]
    d = "".join(ring_d(r) for poly in polys for r in poly)
    countries.append({"id": g.get("id"), "name": name, "d": d})

with open(out, "w") as f:
    f.write("/* Generated by tableau/tools/build_geo.py from Natural Earth 110m (world-atlas@2.0.2). Web Mercator. */\n")
    f.write("window.ONBD_GEO = ")
    json.dump({"w": W, "h": round(H, 1), "countries": countries}, f, separators=(",", ":"))
    f.write(";\n")
print(len(countries), "countries; viewBox", W, round(H, 1))
